# Generated by Django 2.1.7 on 2019-03-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sil', models.IntegerField()),
                ('szc', models.IntegerField()),
                ('int', models.IntegerField()),
                ('zre', models.IntegerField()),
                ('hp', models.IntegerField()),
                ('hpp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Random',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('decsription', models.TextField()),
                ('chance', models.FloatField(default=0.2)),
            ],
        ),
        migrations.CreateModel(
            name='Way',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_from', models.IntegerField()),
                ('id_to', models.IntegerField()),
                ('zdazenie', models.ManyToManyField(to='ProjektRPGtekstowy.Random')),
            ],
        ),
        migrations.AddField(
            model_name='random',
            name='zdazenie',
            field=models.ManyToManyField(to='ProjektRPGtekstowy.Way'),
        ),
        migrations.AddField(
            model_name='event',
            name='way',
            field=models.ManyToManyField(through='ProjektRPGtekstowy.Way', to='ProjektRPGtekstowy.Event'),
        ),
    ]
