# Generated by Django 2.1.7 on 2019-03-12 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProjektRPGtekstowy', '0003_auto_20190311_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='way',
            name='zdazenie',
        ),
        migrations.RemoveField(
            model_name='event',
            name='way',
        ),
        migrations.AddField(
            model_name='player',
            name='curent_state',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=25),
        ),
        migrations.DeleteModel(
            name='Random',
        ),
        migrations.DeleteModel(
            name='Way',
        ),
        migrations.AddField(
            model_name='answers',
            name='end',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='r_end', to='ProjektRPGtekstowy.Event'),
        ),
        migrations.AddField(
            model_name='answers',
            name='start',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='r_start', to='ProjektRPGtekstowy.Event'),
        ),
    ]
