# Generated by Django 2.1.7 on 2019-03-13 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjektRPGtekstowy', '0007_auto_20190312_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='chance',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
