# Generated by Django 2.1.7 on 2019-03-13 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjektRPGtekstowy', '0008_auto_20190313_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='player',
            name='points',
            field=models.ImageField(default=5, upload_to=''),
        ),
    ]
