# Generated by Django 2.1.7 on 2019-03-13 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjektRPGtekstowy', '0009_auto_20190313_1014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='int',
            new_name='inte',
        ),
    ]
