# Generated by Django 2.1.7 on 2019-03-13 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ProjektRPGtekstowy', '0011_auto_20190313_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='user_players',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
