# Generated by Django 2.1.7 on 2019-03-14 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjektRPGtekstowy', '0012_player_user_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_random',
            field=models.BooleanField(default=False),
        ),
    ]
