# Generated by Django 2.1.7 on 2019-03-14 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjektRPGtekstowy', '0013_event_is_random'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_random',
        ),
        migrations.AddField(
            model_name='answers',
            name='is_random',
            field=models.BooleanField(default=False),
        ),
    ]
